### ISSUE TITLE
Link to config on Getting Started page 404s

### ISSUE THREAD

**Issue by adamvictorclever** [tsoa-community/docs#16]
Hi! I'm new to tsoa and started looking through the docs, but I noticed that a link on the Getting Started page is 404ing, specifically at https://github.com/tsoa-community/docs/blame/master/getting-started.md#L66.

I'd open a PR to fix but I'm not actually sure what the correct thing to link to is 😅

**Comment by WoH** [comment]
Fixed, should be up in a sec, thanks for reporting.
