### ISSUE TITLE
"We usually don't want to create a new controller instance for every call" - unsafe?

### ISSUE THREAD

**Issue by ghost** [tsoa-community/docs#18]
[The IOC docs state](https://tsoa-community.github.io/docs/di.html#inversifyjs) "We usually don't want to create a new controller instance for every call" - Why is this safe?

Given a controller like this:
```TS
@Route("users")
@provideSingleton(UsersController)
export class UsersController extends Controller {
  @Get("{userId}")
  public async getUser(
    @Path() userId: number,
    @Query() name?: string
  ): Promise<User> {
	const userService = new UsersService();
    return await userService.get(userId, name);
  }

  @SuccessResponse("201", "Created")
  @Post()
  public async createUser(
    @Body() requestBody: UserCreationParams
  ): Promise<void> {
	const userService = new UsersService();
    this.setStatus(201); // race-condition?
    await userService.create(requestBody);
    return;
  }
}
```

Isn't there now a race-condition with the `setStatus(201)` call potentially affecting another request, maybe even for another route? Or am I confused? - If I'm not, I think the quoted sentence should go away, and we should change the example to use a controller per-requests, since it's unsafe in a lot of cases and the controller reuse is likely an unnecessary optimization anyway.

**Comment by WoH** [comment]
Yes, see: https://github.com/tsoa-community/docs/commit/5d78830849fa69e6e5e5fc9d251bc5624b22d129

**Comment by ghost** [comment]
Oh its not on the website for some reason 🤔

**Comment by WoH** [comment]
Should be there now, thanks for the info.
