### ISSUE TITLE
Update file upload docs

### ISSUE THREAD

**Issue by WoH** [tsoa-community/docs#35]
See https://github.com/lukeautry/tsoa/pull/920

**Comment by TheTimeWalker** [comment]
I have just found out by following the PRs that implement the UploadedFile feature actually isn't as customizable as the method from before. For example the decorator only allows Multer to save to disk with afaik no path setting available. You also can't use any other storage with the decorator.

Wouldn't it be a good idea to keep the old method still in the docs for explanation on how to customize this more? The old explanation allowed you to set your own storage setting for multer which made it convenient.

**Comment by WoH** [comment]
We can append the old way after the newer method if you want to submit a PR.
