### ISSUE TITLE
Document the process of using alternative middlewares (Hapi, Koa) instead of Express

### ISSUE THREAD

**Issue by kuasha420** [tsoa-community/docs#40]
Also, would be a good idea to include documentation regarding how to integrate with other middle wares that aren't officially supported.

**Comment by WoH** [comment]
Are you interested in adding this?

**Comment by kuasha420** [comment]
I would love to but I have no idea how to do this in code. Is there any repo or sample anywhere that I can see, then maybe I'll be able to write the docs.

**Comment by Themis3000** [comment]
I'm seconding this. I just spent hours trying to figure it out only to realize the whole time I just needed to change `routes/middleware` to `koa` in `tsoa.json`. Took me reading the source files to figure that out. If nothing else, in some obvious place in the documentation (maybe in the getting started guide) I think this should at least be mentioned if nothing else. How to get koa's context object in a request is already mentioned in another page so I'd say might as well. If I have time I'll make a pull request for it.
